apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zmjp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0035-tenant/ci10t-777-0035-app/devfile-sample-zmjp@sha256:136a99ac42a88e5557f291c38d34e08ca6c432b49d7c29f2741d18238d84fcd7
        name: my-nodejs
        resources: {}
status: {}
